### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by norro** [ros2-gbp/system_modes-release#1]
Between last update of this repo here (June 16th) and now, I created further releases in the former release repo: https://github.com/microROS/system_modes-release

I suppose I should get this repo here up to date first, before using it for further releases, e.g., for rolling. Is this correct and do you have suggestions on how to do this best, @nuclearsandwich?

**Comment by norro** [comment]
Btw. I am main author and maintainer of the system_modes package at https://github.com/micro-ROS/system_modes as well as the system_modes release repo https://github.com/microROS/system_modes-release

Since this new release infrastructure seems to be pretty new still, I am happy to pilot it with this package.

**Comment by nuclearsandwich** [comment]
> I suppose I should get this repo here up to date first, before using it for further releases, e.g., for rolling. Is this correct and do you have suggestions on how to do this best, @nuclearsandwich?

I have updated this repository with all refs and tags from https://github.com/microROS/system_modes-release.git
To do so I rebased the additions from the rolling release onto the master branch from the other release repository and force pushed the `upstream` branch from that repository. Collisions on this branch can occur even within a single bloom repository when the same version of a package is released into multiple tracks. It only creates a problem if the upstream code actually changes without changing the version number, which is not the case here.

The next step is to ensure that you and any other maintainers have the necessary access to this repository.

By default, I'll add you to a system_modes-release team which has full admin rights on this repository but if there is a logical team which would collect admin access to this repository and some others, (e.g. other repositories associated with the micro-ROS project) please let me know what the team should be called and which other release repositories it should have access to and I can create it once I verify the information.



> Since this new release infrastructure seems to be pretty new still, I am happy to pilot it with this package.

I'm very grateful for your patience thus far as I get this sorted out! :bow:

**Comment by norro** [comment]
Currently there is no logical team to use for this. So for now it should be fine to provide the access just to me.

If you let me know once I have the access rights to this repo, I am happy to try it out.

**Comment by norro** [comment]
@nuclearsandwich Is there anything I can do to fix the release by now?
I am receiving at least two mails about failing builds per day and people start asking already. ;) The master should be ready for a rolling release, it just seems to be missing a new bloom-release.
Thanks in advance!

**Comment by clalancette** [comment]
@norro Just FYI, I know @nuclearsandwich is on vacation this week.  So I expect that there will be no response until next week.  I didn't realize this was what was blocking system_modes; I won't push on https://github.com/micro-ROS/system_modes/issues/44 until you have access again.  Thanks for looking into it!

**Comment by nuclearsandwich** [comment]
@norro apologies for the delay. I've given you direct admin access to this repository. Let me know if you have any further issues with releases.

**Comment by norro** [comment]
Thanks, Steven! I managed to bloom for rolling with this repository and the according PR does look fine to me: https://github.com/ros/rosdistro/pull/26758 *(in fact, it's really trivial only changing one line. but that's a good thing I suppose)*

Should I use this repository for all ros distros in the future then, @nuclearsandwich? Is that how this new repo structure is intended?

**Comment by nuclearsandwich** [comment]
> Should I use this repository for all ros distros in the future then, @nuclearsandwich? Is that how this new repo structure is intended?

That's mostly up to you but I would certainly recommend it. In order for Rolling to get automatic platform updates it must use release repositories in the ros2-gbp organization. Other distributions are optional but it's probably most straightforward for everyone involved to have one active release repository at a time.

**Comment by norro** [comment]
rolloing releases are working now

**Comment by norro** [comment]
Sorry to bother you again, @nuclearsandwich, but [this comment](https://github.com/ros2-gbp/system_modes-release/issues/1#issuecomment-663067739) is not verbose enough for me to do the actual migration, I'm afraid. Could you elaborate on the steps that I need to perform in order to migrate the old release repo to this one? I don't understand well enough which branches to rebase and force-push from which repo to which. :D

Or can you maybe refer to a documentation? I could image that several package maintainers will run into this question soon.

If there is no docu, yet, I am happy to contribute one once I understood what to do.
